### ISSUE TITLE
Missing development branch for the contributors  

### ISSUE THREAD

**Issue by dilumdesilva** [fossasia/open-event-orga-iOS#21]
**Actual Behaviour**
For the moment  **open-event-orga-iOS** project only contains **ipa** branch and **master** branch.
<img width="1027" alt="Screen Shot 2019-03-29 at 3 00 36 AM" src="https://user-images.githubusercontent.com/23298579/55194176-e8a8cc00-51ce-11e9-924a-5e0740a50c0c.png">

**Expected Behaviour**

As mentioned under **branch policy** section of the project readme, **contributors** are supposed to push their changes related PR s to the **development** branch. Since the branch creation is only possible for maintainers or the mentors of the project, It would be much appreciated if one of the mentors/maintainers of the project could create the **development branch**.

<img width="930" alt="Screen Shot 2019-03-29 at 2 54 41 AM" src="https://user-images.githubusercontent.com/23298579/55194389-84d2d300-51cf-11e9-8b2b-bbedf660e1de.png">

**Would you like to work on the issue?**
One of the mentors/maintainers have to work on this.

**Comment by mariobehling** [comment]
As we don't have a release version that is usable this is low priority. There are always glitches here and there in the Readme.md as well. For now we hope to see everyone focus to make the basics work.

**Comment by jogendra** [comment]
@dilum1995 as mentioned in the readme, _For the initialization period all commits go directly to the master branch._ We are at very initial state.

**Comment by dilumdesilva** [comment]
@jogendra , @mariobehling  Noted and thanks for the quick response I will direct my PR s to master branch then
